### ISSUE TITLE
inline edit

### ISSUE THREAD

**Issue by ericxin1982** [cenfun/turbogrid#1]
Hi

Does this support inline edit, means I select the row then I can edit individual cell to change data.

Thanks
Eric Xin

**Comment by cenfun** [comment]
yes, it can edit with custom formatter, see https://cenfun.github.io/turbogrid/formatter.html

**Comment by ericxin1982** [comment]
I do not think that is what I am asking, I meant I can change the cell value when I click specific cell.

**Comment by ericxin1982** [comment]
https://cenfun.github.io/turbogrid/row-add-delete.html

Like this, you can add row, and delete row, but I want to change row cell value, how?

**Comment by cenfun** [comment]
I created a example here https://cenfun.github.io/turbogrid/vue-editor.html
I used Vue components. For text, click cell to start editing.
You can check the data after edited with `exportData()`

**Comment by ericxin1982** [comment]
That is great, I saw it.
If using ES6, how to create InputEditor, this kind of component?
it there any existing example I can learn?

I appreciate it!

Thanks
Eric Xin

**Comment by cenfun** [comment]
`turbogrid` is written in pure native JS, with zero dependencies. So, it can be integrated with any UI framework, such as Vue, React, etc. It is recommended to use these UI components to implement your application, instead of using native ES6 directly.

**Comment by ericxin1982** [comment]
Replied so quick. Are you a chinese?

**Comment by cenfun** [comment]
Yes, 我在深圳

**Comment by ericxin1982** [comment]
厉害，我在汕头。能加微信吗？

**Comment by cenfun** [comment]
具体一点是什么
这个grid的前身本来就是企业级应用里精炼提取出来的独立组件，也是本人开发的
支持高性能的百万级数量的行渲染，也支持强自定义能力，单元测试覆盖90%，质量也可靠，毕竟前身已经在各种企业级应用里了
就看你需要做什么了

**Comment by ericxin1982** [comment]
只能说眼前一亮，特别是思路很吻合，虽说我能力很菜。就是点击row，就有一个浮动的editable row浮在上面修改对应row的值。
我之前是不想准备用 vue3的了，因为国内很多框架都是同质化很高，而且需要打包。
我准备用 alpinejs 搭配qiankun来做动态加载spa，所以一开始看到了 turbogrid, 也才问有没有 es6的editable table row 的这种实现。
我目前也只能以学费的方式合作，因为项目还在构思当中。更多的就是向你请教，一些不会需要手把手教，这样子。

**Comment by ericxin1982** [comment]
你是我看到的代码写的最硬朗，配色最舒服的前端。

**Comment by cenfun** [comment]
分享一点看法，不一定正确
1，对于我个人来说，是从有前端的一开始就入行的，所以用es5，es6这种原生代码直接写组件，没有任何问题
2，如果是写最基础的组件，底层组件，核心框架这些，直接用es5，es6写其实也没问题
3，如果要写应用层，应用组件，那么完全没必要这样，更推荐使用最流行的UI框架写，应该简单，速度快
4，国内很多框架都是同质化很高也没错，所以要用国际上最流行最认可的，其实也就是vue和react这些，alpinejs这种都没听过，一看也就是借鉴vue这些，当然如果要写原生一点的组件，w3c有提供custom elements这样的东西，但没有流行，这些我都有用过并实现了组件库
5，alpinejs没听过，qiankun之前公司有用，但都是特定的场合，所以看你需要实现什么，你的具体情况是什么去选择即可

**Comment by ericxin1982** [comment]
Thanks so much!

**Comment by ericxin1982** [comment]
![image](https://github.com/cenfun/turbogrid/assets/9047436/487c341d-05ad-48ea-be82-523b9e35e1f0)
Sorry to ask again.
这个地方的 option 是静态的，如果要动态的话，是不是就是有个对象事先准备好，然后按照这个key/value套进去就行？

**Comment by cenfun** [comment]
完全可以动态的，我这只是例子，或者做成直接发请求去服务端取都可以
所以为什么要用组件，全部都可以做成异步的

**Comment by ericxin1982** [comment]
YYDS

**Comment by ericxin1982** [comment]
![image](https://github.com/cenfun/turbogrid/assets/9047436/0528174b-e83c-4834-b596-752af113a02d)

这个完整地址是在哪里，想深入学习看看。谢谢

**Comment by cenfun** [comment]
https://github.com/cenfun/vine-ui

**Comment by ericxin1982** [comment]
我看你用vue3很熟练，我有个疑问想请假你，我google找了很久也不是完全能搞明白。
就是vue3 能不能不打包，然后就直接用起来。
生产环境下，我就是想改了前端代码，刷f5就能直接看到变化。

**Comment by cenfun** [comment]
你可以看到我这个例子 https://cenfun.github.io/turbogrid/vue-editor.html
压根就是直接写代码直接运行的啊
因为vue已经用了prod的包，vine-ui的组件也已经打成dist包
这是另一个学问了，打包的方式，得搞清楚什么事runtime运行时的代码，什么是源代码，就是未编译的
浏览器里面无非就是要能找到组件的引用，因为不确定什么时候载入，所以可以直接挂到全局比如window上
那么打包的时候，直接用UMD模式就行了，支持全部载入方式包括全局
开发前端，不明白打包技术是不行的，永远要掌握构建工具

**Comment by ericxin1982** [comment]
turbogrid cdn
vue3 cdn
vine-ui cdn

各种关联的html文件，vine-ui标签化
各种自己写的js文件，有我自己的逻辑，turbogrid组件，vine-ui组件

然后我自己的js逻辑，随时改，随时生效，我的意思是这样，是否可行？

**Comment by cenfun** [comment]
完全可行
这样是用vue在线编译组件，尤其是它的模板，所以vue的包里需要都包含编译模块
至于turbogrid 无所谓它本身就是直接运行的
结果就是，1，多余包含编译模块体积大  2，需要总是在线编译，无端损耗性能  3，你写的vue组件还是源码的形式，无编译优化
所以得把项目做成开发模式，比如用vue的vite这样的构建工具，或者webpack，这些都是直接热加载的，改完代码自动刷新
开发完了，再打包，这样代码都是优化过的，体积也是压缩过的，可以做到最优化，现代的前端都是这样的，需要编译
不像以前的年代了，那个时候没有编译的，写完基本就直接运行

**Comment by ericxin1982** [comment]
![image](https://github.com/cenfun/turbogrid/assets/9047436/36c1a6c8-67e4-4216-8989-47d0214853d8)

是这样子是吗？

你用 runtime 的库，因为没有显式的 template 的tag?

**Comment by ericxin1982** [comment]
我需要一个平台可以做我的业务。

portal 的页面这样，spa的。这个portal 需要一个nav sidebar。
nav sidebar 最多三层，sidebar icon 一层，中间一层，最后选项为第三层。
最后一层除了 menu 本身的名字，还有对应的 url, 还要支持auth 相关的信息，目前我也没什么概念

组件来说，我还需要

1. Form
2. 穿梭框
3. nav sidebar item 点击产生的 Page
另外 Select (support multiple items selected) 这个可不可以实现？

你有时间，有兴趣帮我搞一下吗?  我预算2000封顶

[nav.zip](https://github.com/cenfun/turbogrid/files/14800837/nav.zip)

**Comment by cenfun** [comment]
没有兴趣做这些

**Comment by ericxin1982** [comment]
我使用的时候有两个疑问请教一下：

1. 就是有些列我不想有 inline edit, 怎么弄？
2. 然后如果这个turbogrid 放在一个 modal 里面，然后modal 有一个按钮是edit，没点之前turbogrid是不能编辑的，点了之后才能编辑，怎么实现？

**Comment by cenfun** [comment]
1，可以自行标记，是否能编辑，比如
- 整列是否编辑，columnItem.editable = true/false
- 整行是否编辑，rowItem.editable = true/false
- 单个格子，可以拼列id，比如 rowItem.name_editable = true/false (假设name是一个列的id)
2，同上，增加一个总的editable即可，然后重新渲染一遍grid即可， grid.rerender();

**Comment by ericxin1982** [comment]
还是按照 vue-editor 这个例子，如果我整列不参与 formater, 也就不参与编辑的话
![image](https://github.com/cenfun/turbogrid/assets/9047436/5a3d08e6-feee-45c0-899d-47d981ed92c3)
这里的的 formater 能不能就不赋值这个对象就等于对应的列不可编辑，只能看?

还是以这个vue-editor 为例

整行是否编辑，rowItem.editable = true/false
单个格子，可以拼列id，比如 rowItem.name_editable = true/false (假设name是一个列的id)

同上，增加一个总的editable即可，然后重新渲染一遍grid即可， grid.rerender();

这些加在哪里，turbogrid 我看option, api 什么，ctrl+F 都没有这些个 editable 属性存在。
我要是新加属性，我加在下面哪里我也不是很肯定，能不能详细指导一下？

var grid = new Grid(container);
grid.setData(data);
grid.setOption(options);
grid.setFormatter(formatters);
grid.bind("[event type]", handler);

**Comment by cenfun** [comment]
直接看例子吧，已经更新上去了，几分钟的事，刷一下防止缓存
https://cenfun.github.io/turbogrid/vue-editor.html

这东西需要一点基础的，而且要懂vue，否则讲了方案也不一定懂就浪费时间，没有那么多时间从最基础的讲

**Comment by ericxin1982** [comment]
Thanks
